# Generated by Django 4.2.7 on 2023-11-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeBudget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
