# Generated by Django 4.2.7 on 2023-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeBudget', '0006_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='earning',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
