# Generated by Django 4.2.7 on 2023-12-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeBudget', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userv2',
        ),
    ]
